[tool.poetry]
name = "gym-quarto"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
